config/routes.rb
Rails.application.routes.draw do
  resources :flats# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    # no need for app/views/flats/create.html.erb
    if @flat.save
      redirect_to flats_path(@flat)
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

      redirect_to flats_path(@flat)

  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Flats</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

  <%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit %>
<% end %>

</body>
</html>

app/views/flats/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Show All Flats</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>

  <nav class="navbar navbar-light bg-light d-flex justify-content-between flex-row">

    <%= link_to 'Simple Airbnb', flats_path%>

    <div class="d-flex flex-row justify-content-around align-items-center">
      <form class="form-inline mr-4">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>

      <form class="form-inline">
        <button class="btn btn-outline-primary" type="button">
          <%= link_to 'New Flat', new_flat_path%>
        </button>
      </form>
    </div>

  </nav>

  <div class="d-flex justify-content-center flex-column">

    <div class="mt-3 ml-5">
      <h1 class="text-left">All our flats</h1>
      <p class="text-left">All <%=@flats.count%> flats</p>
    </div>

    <div class="d-flex flex-row flex-wrap justify-content-start p-2 ml-5 justify-self-center">

      <% @flats.each do |flat| %>
      <div class="card m-2" style="width: 18rem;">
        <img class="card-img-top" src="https://source.unsplash.com/286x190/?<%= flat.name %>" alt="Card image cap">
        <div class="card-body d-flex flex-column justify-content-start align-items-center">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.address %></p>
          <div class="d-flex flex-row justify-content-start">
            <i class="small material-icons">attach_money</i>
            <p class="card-text mr-3"><%=flat.price_per_night%></p>
            <i class="small material-icons">airline_seat_flat</i>
            <p class="card-text"><%=flat.number_of_guests%></p>
           </div>
        </div>

        <div class="card-footer">
          <div class="btn btn-link">
            <%= link_to 'Edit', edit_flat_path(flat)%>
          </div>
          <div class="btn btn-link">
            <%= link_to 'More Info', flat_path(flat)%>
          </div>
          <div class="btn btn-link">
            <%= link_to "Remove",
                  flat_path(flat),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
   </div>

</body>
</html>

app/views/flats/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Create New Flat</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

  <%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :price_per_night %>
  <%= f.text_field :price_per_night %>
  <%= f.label :number_of_guests %>
  <%= f.text_field :number_of_guests %>
  <%= f.submit %>
<% end %>

</body>
</html>

app/views/flats/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Show Flat</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

  <nav class="navbar navbar-light bg-light d-flex justify-content-between flex-row">

    <%= link_to 'Simple Airbnb', flats_path%>

    <div class="d-flex flex-row justify-content-around align-items-center">
      <form class="form-inline mr-4">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>

      <form class="form-inline">
        <button class="btn btn-outline-primary" type="button">Add Flat</button>
      </form>
    </div>
  </nav>

  <div class="card m-2" style="width: 100%;">
    <img class="card-img-top" src="https://source.unsplash.com/1600x900/?<%= @flat.name %>" alt="Card image cap">
    <div class="card-body d-flex flex-column justify-content-start align-items-start">
      <h2 class="card-title"><%= @flat.name %></h2>
      <h3 class="card-text"><%= @flat.address %></h3>
      <div class="d-flex flex-row justify-content-start">
        <i class="large material-icons">attach_money</i>
        <h4 class="card-text mr-3"><%=@flat.price_per_night%></h4>
        <i class="large material-icons">airline_seat_flat</i>
        <h4 class="card-text"><%=@flat.number_of_guests%></h4>
       </div>
    </div>

    <div class="card-footer">
      <div class="btn btn-link">
        <%= link_to 'Edit', edit_flat_path(@flat)%>
      </div>
      <div class="btn btn-link">
        <%= link_to "Remove",
              flat_path(@flat),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>